# Generated by Django 4.0 on 2022-02-23 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dispositivo', models.CharField(max_length=100)),
                ('numero_ip', models.CharField(max_length=15)),
                ('universo', models.PositiveSmallIntegerField(default=0)),
                ('tamano_paquetes', models.PositiveSmallIntegerField(default=512)),
                ('matriz_x', models.PositiveSmallIntegerField(default=1)),
                ('matriz_y', models.PositiveSmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('patch', models.CharField(default='sin patch', max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDispositivosEnShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(choices=[('Abajo-Izquierda', 'Abajo-Izquierda'), ('Abajo', 'Abajo'), ('Abajo-Derecha', 'Abajo-Derecha'), ('Izquierda', 'Izquierda'), ('Centro', 'Centro'), ('Derecha', 'Derecha'), ('Arriba-Izquierda', 'Arriba-Izquierda'), ('Arriba', 'Arriba'), ('Arriba-Derecha', 'Arriba-Derecha')], default='Centro', max_length=20)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledsup.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_showroom', models.CharField(max_length=100)),
                ('matriz_x_total', models.PositiveSmallIntegerField(default=1)),
                ('matriz_y_total', models.PositiveSmallIntegerField(default=1)),
                ('url_server', models.CharField(max_length=200)),
                ('dispositivos', models.ManyToManyField(through='ledsup.OrdenDispositivosEnShowroom', to='ledsup.Dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='ordendispositivosenshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledsup.showroom'),
        ),
    ]
