# Generated by Django 4.0.3 on 2022-03-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledsup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='patch',
            field=models.TextField(default='Sin patch', max_length=600),
        ),
    ]
