# Generated by Django 4.0.3 on 2022-03-20 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledsup', '0002_alter_dispositivo_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='matriz_x',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='matriz_y',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='matriz_x_total',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='matriz_y_total',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
