# Generated by Django 4.0.3 on 2022-04-02 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledsup', '0003_alter_dispositivo_matriz_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='matriz_x_total',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='matriz_y_total',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='matriz_x',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(34)]),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='matriz_y',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(34)]),
        ),
    ]
