# Generated by Django 4.0.3 on 2022-04-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledsup', '0004_remove_showroom_matriz_x_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_led',
            field=models.CharField(choices=[('RGB', 'RGB'), ('RBG', 'RBG'), ('BRG', 'BRG'), ('BGR', 'BGR'), ('GRB', 'GRB'), ('GBR', 'GBR')], default='RGB', max_length=5),
        ),
    ]
