# Generated by Django 4.1.3 on 2023-04-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledsup', '0005_dispositivo_tipo_led'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
