# Generated by Django 3.2.7 on 2021-09-21 01:17

import django.utils.timezone
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210919_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosproducto',
            name='url_video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.ruta_imagen_donde_guardar, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
    ]
