# Generated by Django 4.1.3 on 2025-05-11 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210919_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='videosproducto',
            name='url_video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.CreateModel(
            name='ImagenesGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_imagen', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, verbose_name='img')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.galeria')),
            ],
        ),
    ]
