# Generated by Django 4.1.3 on 2025-05-22 00:54

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_galeria_videosproducto_url_video_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeria',
            new_name='Evento',
        ),
        migrations.RenameModel(
            old_name='ImagenesGaleria',
            new_name='ImagenesEventos',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre',
            new_name='nombre_evento',
        ),
        migrations.RenameField(
            model_name='imageneseventos',
            old_name='galeria',
            new_name='evento',
        ),
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.ruta_imagen_producto, verbose_name='img'),
        ),
    ]
