# Generated by Django 4.1.3 on 2025-06-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_errores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errores',
            options={'verbose_name': 'Error', 'verbose_name_plural': 'Errores'},
        ),
    ]
