# Generated by Django 5.2.1 on 2025-06-15 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_errores_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='detalle',
            new_name='pie_de_imagen',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_de_evento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Evento'),
        ),
    ]
