# Generated by Django 5.2.1 on 2025-06-16 00:42

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_detalle_evento_pie_de_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(default=0, upload_to=web.models.ruta_imagen_evento),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImagenesEventos',
        ),
    ]
