# Generated by Django 4.1.3 on 2025-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_evento_imagen_alter_imagenesproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
