# Generated by Django 4.1.3 on 2025-06-22 06:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_imagenesproducto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
